# GitHub Pages configuration
title: sushiApp - 利用規約・プライバシーポリシー
description: sushiApp（寿司アプリ）の利用規約とプライバシーポリシー
author: Hideaki Murasawa
baseurl: ""
url: ""

# Theme
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

